apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mprahl-test.fullname" . }}
data:
  lookup-result: '{{ index (lookup "v1" "Secret" "openshift-config" "pull-secret").data ".dockerconfigjson" | b64dec }}'
